### ISSUE TITLE
Q: Given AND When Then?

### ISSUE THREAD

**Issue by whernebrink** [hirezio/given#8]
Just a question. I could have bet I saw somewhere, a coulple of months ago that there were a new version where one could do Given, *And*, When, Then? Did I dream that there were the `And` added? :)

**Comment by shairez** [comment]
I think the version of "given" by Justin Searls had an And function.
But I decided not to implement it in this version.

At any cases, I suggest looking into - 
https://github.com/hirezio/single

It doesn't have an "and" function, but it's the future of single action tests IMO :)
